#!/bin/sh


echo "Compiling"
mvn compile
if [ $? -ne 0 ]; then
  echo "Compilation failed"
  exit 1
fi

echo "Checkstyle"
mvn checkstyle:check
if [ $? -ne 0 ]; then
  echo "Checkstyle violations found"
  # exit 1 
fi




echo "SpotBugs analysis..."
mvn spotbugs:check
if [ $? -ne 0 ]; then
  echo "SpotBugs issues found."
  #exit 1
fi

exit 0